import { CSSProperties } from "react";
import { colors, typography, spacing } from "../appStyles";

export const eventRegistrationStyles: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: "calc(70px + 2rem)",
    paddingBottom: spacing["2xl"],
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    background: "linear-gradient(-45deg, #111, #222, #333, #222)",
    backgroundSize: "400% 400%",
    animation: "gradientBG 15s ease infinite",
    position: "relative",
    overflow: "hidden",
  },
  header: {
    width: "100%",
    maxWidth: "900px",
    marginBottom: spacing.xl,
  },
  title: {
    fontSize: "4rem",
    textAlign: "center",
    color: colors.white,
    marginBottom: spacing.md,
    fontWeight: typography.fontWeights.bold,
    fontFamily: typography.titleFontFamily,
    textTransform: "uppercase",
    lineHeight: 1.1,
  },
  subtitle: {
    fontSize: "1.2rem",
    textAlign: "center",
    color: "rgba(255, 255, 255, 0.7)",
    maxWidth: "700px",
    margin: "0 auto",
    lineHeight: 1.6,
  },
  formContainer: {
    width: "100%",
    maxWidth: "600px",
    background: "rgba(28, 28, 30, 0.95)",
    borderRadius: "1rem",
    padding: spacing.xl,
    boxShadow: "0 8px 30px rgba(0, 0, 0, 0.3)",
    marginTop: spacing.lg,
    position: "relative",
    zIndex: 2,
    backdropFilter: "blur(10px)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  formHeader: {
    marginBottom: spacing.xl,
    textAlign: "center",
  },
  formTitle: {
    fontSize: "1.5rem",
    color: colors.white,
    marginBottom: spacing.sm,
    fontWeight: typography.fontWeights.semibold,
  },
  stepIndicator: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: "400px",
    margin: `${spacing.md} auto`,
  },
  step: {
    width: "2rem",
    height: "2rem",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255, 255, 255, 0.1)",
    color: "rgba(255, 255, 255, 0.6)",
    fontWeight: typography.fontWeights.medium,
    position: "relative",
    zIndex: 2,
  },
  stepActive: {
    background: colors.primary,
    color: colors.white,
  },
  stepCompleted: {
    background: colors.success,
    color: colors.white,
  },
  stepLine: {
    flex: 1,
    height: "2px",
    background: "rgba(255, 255, 255, 0.1)",
    margin: "0 0.5rem",
  },
  stepLineActive: {
    background: colors.primary,
  },
  formGroup: {
    marginBottom: spacing.lg,
  },
  label: {
    display: "block",
    marginBottom: spacing.xs,
    color: colors.white,
    fontWeight: typography.fontWeights.medium,
    fontSize: "0.95rem",
  },
  input: {
    width: "100%",
    padding: "0.75rem",
    borderRadius: "0.5rem",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    fontSize: "1rem",
    transition: "border-color 0.2s ease",
    outline: "none",
    background: "rgba(255, 255, 255, 0.08)",
    color: colors.white,
  },
  inputFocus: {
    borderColor: colors.primary,
    boxShadow: `0 0 0 2px ${colors.primaryLight}`,
  },
  select: {
    width: "100%",
    padding: "0.75rem",
    borderRadius: "0.5rem",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    fontSize: "1rem",
    transition: "border-color 0.2s ease",
    outline: "none",
    appearance: "none",
    backgroundImage: "url(\"data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'%3e%3c/polyline%3e%3c/svg%3e\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 0.7rem center",
    backgroundSize: "1rem",
    paddingRight: "2.5rem",
    background: "rgba(255, 255, 255, 0.08)",
    color: colors.white,
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: spacing.xl,
    gap: "1rem",
  },
  backButton: {
    padding: `${spacing.sm} ${spacing.md}`,
    border: "1px solid rgba(255, 255, 255, 0.2)",
    borderRadius: "0.5rem",
    background: "rgba(255, 255, 255, 0.08)",
    color: colors.white,
    fontWeight: typography.fontWeights.medium,
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  qrCodeContainer: {
    textAlign: "center",
    marginTop: spacing.xl,
  },
  qrCode: {
    maxWidth: "220px",
    borderRadius: "0.5rem",
    padding: spacing.md,
    background: "rgba(255, 255, 255, 0.9)",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.2)",
    margin: "0 auto",
  },
  paymentInfo: {
    marginTop: spacing.lg,
    padding: spacing.md,
    background: "rgba(255, 255, 255, 0.1)",
    borderRadius: "0.5rem",
    color: colors.white,
    fontWeight: typography.fontWeights.medium,
    textAlign: "center",
    border: "1px solid rgba(255, 255, 255, 0.2)",
  },
  errorText: {
    color: "#ff6b6b",
    fontSize: "0.875rem",
    marginTop: spacing.xs,
  },
  successContainer: {
    textAlign: "center",
    marginTop: spacing.xl,
  },
  successIcon: {
    color: colors.success,
    fontSize: "3rem",
    marginBottom: spacing.md,
  },
  successMessage: {
    color: colors.white,
    fontSize: "1.25rem",
    fontWeight: typography.fontWeights.semibold,
    marginBottom: spacing.md,
  },
  highlightedText: {
    background: "linear-gradient(45deg, #FF4D4D, #FF9D4D)",
    color: colors.white,
    padding: "0.25rem 0.5rem",
    borderRadius: "0.25rem",
    fontWeight: typography.fontWeights.bold,
    display: "inline-block",
    margin: "0 0.25rem",
  },
  shirtPreviewSection: {
    marginBottom: spacing.lg,
    textAlign: "center",
  },
  shirtPreviewTitle: {
    fontSize: "1.1rem",
    fontWeight: typography.fontWeights.semibold,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  shirtGalleryContainer: {
    width: "100%",
    padding: spacing.md,
    background: "rgba(0, 0, 0, 0.3)",
    borderRadius: "0.75rem",
    marginBottom: spacing.lg,
    position: "relative",
    overflow: "hidden",
    aspectRatio: "4/3",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  shirtImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
    transition: "opacity 0.3s ease",
  },
  galleryNavButton: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(0, 0, 0, 0.5)",
    color: colors.white,
    border: "none",
    borderRadius: "50%",
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 5,
    transition: "background 0.2s ease",
  },
  galleryPrevButton: {
    left: "10px",
  },
  galleryNextButton: {
    right: "10px",
  },
  galleryDots: {
    display: "flex",
    justifyContent: "center",
    gap: "8px",
    position: "absolute",
    bottom: "10px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 5,
  },
  galleryDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    border: "none",
    padding: 0,
    cursor: "pointer",
  },
  galleryActiveDot: {
    background: colors.white,
  },
  galleryInactiveDot: {
    background: "rgba(255, 255, 255, 0.5)",
  },
  sizeGuideButton: {
    background: "transparent",
    color: colors.primary,
    border: "none",
    fontSize: "0.85rem",
    padding: `${spacing.xs} ${spacing.sm}`,
    marginTop: "0.5rem",
    cursor: "pointer",
    textDecoration: "underline",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    backdropFilter: "blur(5px)",
  },
  modalContent: {
    width: "90%",
    maxWidth: "900px",
    maxHeight: "90vh",
    background: "rgba(30, 30, 30, 0.9)",
    borderRadius: "0.75rem",
    padding: spacing.lg,
    position: "relative",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  modalCloseButton: {
    position: "absolute",
    top: "15px",
    right: "15px",
    background: "rgba(0, 0, 0, 0.5)",
    color: colors.white,
    border: "none",
    borderRadius: "50%",
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 10,
  },
  modalImageContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "70vh",
    width: "100%",
  },
  modalImage: {
    maxWidth: "100%",
    maxHeight: "100%",
    objectFit: "contain",
  },
};

export const eventRegistrationMediaStyles = {
  sm: {
    title: {
      fontSize: "4.5rem",
    },
    formContainer: {
      padding: spacing["2xl"],
    },
    shirtGalleryContainer: {
      aspectRatio: "16/9",
    },
    buttonContainer: {
      flexDirection: "column" as const,
      gap: "0.75rem",
    }
  },
  md: {
    title: {
      fontSize: "5.5rem",
    },
    subtitle: {
      fontSize: "1.35rem",
    },
    modalContent: {
      width: "80%",
    },
    buttonContainer: {
      flexDirection: "row" as const,
      gap: "1rem",
    }
  },
  lg: {
    title: {
      fontSize: "7rem",
    },
  },
};

export default eventRegistrationStyles; 